# Generated by Django 5.0 on 2024-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('change_compared_to_lastyear', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.CharField(max_length=200)),
                ('values', models.IntegerField()),
                ('twelve_month_change', models.DecimalField(decimal_places=2, max_digits=50)),
                ('three_month_change', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
