# Generated by Django 5.0 on 2024-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseValueGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('akl_house_value_growth', models.DecimalField(decimal_places=3, max_digits=50)),
                ('nz_house_value_growth', models.DecimalField(decimal_places=3, max_digits=50)),
            ],
        ),
    ]
