# Generated by Django 5.0 on 2024-01-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0003_averagerentalgrowth'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('three_year_rate', models.DecimalField(decimal_places=2, max_digits=50)),
                ('four_year_rate', models.DecimalField(decimal_places=2, max_digits=50)),
                ('five_year_rate', models.DecimalField(decimal_places=2, max_digits=50)),
            ],
        ),
    ]
