# Generated by Django 5.0 on 2024-01-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0005_alter_mortgagerates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyincome',
            name='region',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
