# Generated by Django 5.0 on 2024-01-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0006_familyincome_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageHouseValueNZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_2003', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2004', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2005', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2006', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2007', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2008', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2009', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2010', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2011', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2012', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2013', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2014', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2015', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2016', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2017', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2018', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2019', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2020', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2021', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2022', models.DecimalField(decimal_places=1, max_digits=50)),
                ('year_2023', models.DecimalField(decimal_places=1, max_digits=50)),
            ],
        ),
    ]
