# Generated by Django 5.0 on 2024-01-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0007_averagehousevaluenz'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageHouseValueCHCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('house_value', models.IntegerField()),
            ],
        ),
    ]
