# Generated by Django 5.0 on 2024-02-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0008_averagehousevaluechch'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeanHouseValueSuburbsCHCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='meanhousevaluesuburbschch',
            constraint=models.UniqueConstraint(fields=('suburb', 'year', 'month'), name='primary_key_of_suburbs_CHCH'),
        ),
    ]
