# Generated by Django 5.0 on 2024-02-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0009_meanhousevaluesuburbschch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AverageHouseValueCHCH',
        ),
    ]
