# Generated by Django 5.0 on 2024-02-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0011_meanhousevaluesuburbschch_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meanhousevaluesuburbschch',
            name='month',
        ),
        migrations.RemoveField(
            model_name='meanhousevaluesuburbschch',
            name='year',
        ),
        migrations.RemoveConstraint(
            model_name='meanhousevaluesuburbschch',
            name='primary_key_of_suburbs_CHCH',
        ),
    ]
