# Generated by Django 5.0 on 2024-02-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0014_mortgagerates_mortgage_rate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgagerates',
            name='date',
        ),
    ]
