# Generated by Django 5.0 on 2024-02-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0015_remove_mortgagerates_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgagerates',
            old_name='mortgage_rate_date',
            new_name='date',
        ),
    ]
