# Generated by Django 5.0 on 2024-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0016_rename_mortgage_rate_date_mortgagerates_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerentalgrowth',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='familyincome',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='housevaluegrowth',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
