# Generated by Django 5.0 on 2024-02-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0017_averagerentalgrowth_date_familyincome_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerentalgrowth',
            name='year',
        ),
        migrations.RemoveField(
            model_name='familyincome',
            name='year',
        ),
        migrations.RemoveField(
            model_name='housevaluegrowth',
            name='year',
        ),
    ]
