# Generated by Django 5.0 on 2024-02-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0018_remove_averagerentalgrowth_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeanHouseValueSuburbsCHCH',
            new_name='ChristchurchSuburbMeanHouseValue',
        ),
    ]
